name: Test
on:
  push:
    branch:
      - master
jobs:
  test:
    runs-on: macos-12
    permissions:
      contents: read
    steps:
      - name: Run actions/checkout for this repo
        uses: actions/checkout@v3
        with:
          path: checkout
          persist-credentials: false
      - name: run tests
        run: |
          brew update && brew install podman
          podman machine init
          podman machine start
          podman info
          podman version
