name: Test
on:
  push:
    branch:
      - master
jobs:
  systemd_podman_echo_server_demo:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Run actions/checkout for this repo
        uses: actions/checkout@v3
        with:
          path: checkout
          persist-credentials: false
      - name: Run an echo server with podman in a user systemd service
        run: |
          podman pull ghcr.io/eriksjolund/socket-activate-echo:latest
          mkdir -p ~/.config/systemd/user
          podman version
          go env
