name: Test
env:
  PODMAN_HOST: tcp://127.0.0.1:3333
on:
  push:
    branch:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout for this repo
        uses: actions/checkout@v3
        with:
          path: checkout
          persist-credentials: false
      - name: run tests
        run: |
          curl -fsSL -o podman-linux-amd64.tar.gz https://github.com/mgoltzsche/podman-static/releases/latest/download/podman-linux-amd64.tar.gz
          curl -fsSL -o podman-linux-amd64.tar.gz.asc https://github.com/mgoltzsche/podman-static/releases/latest/download/podman-linux-amd64.tar.gz.asc
          gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 0CCF102C4F95D89E583FF1D4F8B5AF50344BB503
          gpg --batch --verify podman-linux-amd64.tar.gz.asc podman-linux-amd64.tar.gz
          tar -xzf podman-linux-amd64.tar.gz
          sudo cp -r podman-linux-amd64/usr podman-linux-amd64/etc /
          /usr/local/bin/podman version
